# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='example.proto',
  package='',
  serialized_pb='\n\rexample.proto\"\x88\x01\n\x07\x45xample\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x1f\n\x06nested\x18\x02 \x01(\x0b\x32\x0f.Example.Nested\x12\x0e\n\x06values\x18\x03 \x03(\t\x12&\n\rnested_values\x18\x04 \x03(\x0b\x32\x0f.Example.Nested\x1a\x17\n\x06Nested\x12\r\n\x05value\x18\x01 \x01(\t')




_EXAMPLE_NESTED = descriptor.Descriptor(
  name='Nested',
  full_name='Example.Nested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Example.Nested.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=131,
  serialized_end=154,
)

_EXAMPLE = descriptor.Descriptor(
  name='Example',
  full_name='Example',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='Example.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nested', full_name='Example.nested', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='values', full_name='Example.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nested_values', full_name='Example.nested_values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXAMPLE_NESTED, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=154,
)

_EXAMPLE_NESTED.containing_type = _EXAMPLE;
_EXAMPLE.fields_by_name['nested'].message_type = _EXAMPLE_NESTED
_EXAMPLE.fields_by_name['nested_values'].message_type = _EXAMPLE_NESTED
DESCRIPTOR.message_types_by_name['Example'] = _EXAMPLE

class Example(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Nested(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _EXAMPLE_NESTED
    
    # @@protoc_insertion_point(class_scope:Example.Nested)
  DESCRIPTOR = _EXAMPLE
  
  # @@protoc_insertion_point(class_scope:Example)

# @@protoc_insertion_point(module_scope)
